spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/states
    username: root
    password: pass@word1
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
